In [1]:
import matplotlib
%matplotlib tk
%autosave 180
%load_ext autoreload
%autoreload 2

import nest_asyncio

%config Completer.use_jedi = False

#
import matplotlib.pyplot as plt
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# 
import matplotlib.cm as cm
import numpy as np
import os
from tqdm import tqdm

#
import sys
sys.path.append('/home/cat/code/gerbil/')

# 
from utils.track import track
from utils.convert import convert
from utils.ethogram import ethogram
from utils.database import database
from utils.ethogram import ethogram

Autosaving every 180 seconds


In [4]:
######################################################
############# LOAD ANIMAL DATABASE ###################
######################################################
cohort = database.CohortProcessor()
cohort.fname_spreadsheet = '/mnt/b3a68699-495d-4ebb-9ab1-ac74f11c68c5/gerbil/cohort2/database.xlsx'
cohort.fname_spreadsheet = '/media/cat/4TBSSD/dan/cohort2/P21_P28/database.xlsx'
cohort.load_database()

# print (list(zip(cohort.PDays,cohort.Start_times))[0])
# print (list(zip(cohort.PDays,cohort.Start_times))[1])
# print (list(zip(cohort.PDays,cohort.Start_times))[100])

DF:     Unnamed: 0  Cohort NN Type                                   Filename Dev Day  # of Gerbils Time of Light Switch  Shaved?  Predicted?                                   Slp filename Start time
0           0       2     Day  2020_07_20_09_53_59_813912_compressed.mp4     P15             6                  NaN        1           1  2020_07_20_09_53_59_813912_compressed_Day.slp   09:53:59
1           1       2     Day  2020_07_20_10_16_08_629297_compressed.mp4     P15             6                  NaN        1           1  2020_07_20_10_16_08_629297_compressed_Day.slp   10:16:08
2           2       2     Day  2020_07_20_10_38_20_043555_compressed.mp4     P15             6                  NaN        1           1  2020_07_20_10_38_20_043555_compressed_Day.slp   10:38:20
3           3       2     Day  2020_07_20_11_00_31_566455_compressed.mp4     P15             6                  NaN        1           1  2020_07_20_11_00_31_566455_compressed_Day.slp   11:00:31
4           4       

In [9]:
######################################################
############# PREPROCESS FEATURE TRACKS ##############
######################################################
cohort.n_cores = 30
cohort.parallel = False
cohort.interpolate_flag = False
cohort.preprocess_feature_tracks()



100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 939/939 [00:00<00:00, 72835.82it/s]


In [10]:
#########################################################
############## PREPROCESS HUDDLES #######################
#########################################################

# 
cohort.parallel = False
cohort.fix_track_flag = True
cohort.interpolate_flag = True
cohort.overwrite_flag = False
cohort.preprocess_huddle_tracks()



100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 939/939 [00:00<00:00, 110024.90it/s]


In [182]:
######################################################
########## TIME IN PROXIMITY BEHAVIOR ################
######################################################

#
names = ['female','male','pup1','pup2','pup3','pup4']
cohort.track_type = 'features'
n_partitions = 24
behavior_name = 'time in proximity'

# select animals
cohort.animals = [0,5]


#
cohort.animals_interacting = ''+names[cohort.animals[0]] + " " + names[cohort.animals[1]]
cohort.get_pairwise_interaction_time(cohort.animals[0], cohort.animals[1])

#
cohort.format_behavior()
ethogram.plot_ethogram_hourly(n_partitions, 
                              behavior_name,
                              cohort,
                              vmax=50)


100%|██████████| 1500/1500 [00:03<00:00, 468.65it/s]


res:  (1500,)
[[15.  9.  0.]
 [15. 10.  0.]
 [15. 10.  0.]
 ...
 [30.  9.  0.]
 [30.  9.  0.]
 [30. 10.  0.]]
start day:  15.0
start time:  9.0


In [191]:
################################################
########### CREATE ROI OF INTEREST #############
################################################
# need to select 1 video and 1 slp for visualization purposes;
# make sure the video is shirnk cropped and matches the traces from the slop also.
cohort.fname_video ='/media/cat/4TBSSD/dan/cohort2/P21_P28/2020_07_26_00_05_52_835502_compressed_defished_shrink_cropped.mp4'
cohort.fname_slp_npy =  '/media/cat/4TBSSD/dan/cohort2/P21_P28/features/2020_07_26_00_05_52_835502_compressed_Night_spine.npy'

#
cohort.load_video()

#
cohort.set_roi()

print ("rectangular coords: ", cohort.rect_coords)
print ("circular coords: ", cohort.circle_coords)


(28802, 6, 2)
rectangular coords:  [[ 56.22456576 383.63636364]
 [267.04342432 608.18181818]]
circular coords:  [[155.3808933  504.54545455]
 [223.27171216 392.72727273]]


In [197]:
################################################
########### COMPUTE CIRCLE OCCUPANCY ###########
################################################

#
behavior_name = 'huddle - circular'

# select animals
cohort.animals = 0


#
cohort.get_circle_occupancy(cohort.animals)

#
cohort.format_behavior()
ethogram.plot_ethogram_hourly(n_partitions, 
                              behavior_name,
                              cohort,
                              vmax=50)


100%|██████████| 1500/1500 [00:00<00:00, 3507.42it/s]


res:  (1500,)
[[15.  9.  0.]
 [15. 10.  0.]
 [15. 10.  0.]
 ...
 [30.  9.  0.]
 [30.  9.  0.]
 [30. 10.  0.]]
start day:  15.0
start time:  9.0


In [198]:
################################################
########### COMPUTE RECTANGLE OCCUPANCY ########
################################################

#
behavior_name = 'food hopper occupancy - rectangle'

# select animals
cohort.animals = 0

#
cohort.get_rectangle_occupancy(cohort.animals)

#
cohort.format_behavior()
ethogram.plot_ethogram_hourly(n_partitions, 
                              behavior_name,
                              cohort,
                              vmax=50)


100%|██████████| 1500/1500 [00:00<00:00, 3714.08it/s]


res:  (1500,)
[[15.  9.  0.]
 [15. 10.  0.]
 [15. 10.  0.]
 ...
 [30.  9.  0.]
 [30.  9.  0.]
 [30. 10.  0.]]
start day:  15.0
start time:  9.0
