In [1]:
%matplotlib tk
%load_ext autoreload
%autoreload 2
#
import matplotlib.pyplot as plt

#
from utils import GerbilPCA
import glob
import numpy as np

/home/cat/miniconda3/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# 
fname2 = '/home/cat/Downloads/npy_files (1)/npy_files/cohort2_foodhopper.npy'
data2 = np.load(fname2)
print (data2.shape)



(112, 86400)


In [3]:
behaviors = [

    # FOODHOPPER PROXIMITY
    'foodhopper_proximity',

    # # WATERSPOUT PROXIMITY
    #'waterspout_proximity',

    # # PAIRWISE PROXIMITY
   #'pairwise_proximity',

]




In [4]:
#
g = GerbilPCA(root_dir, 
              behaviors)

#
#g.periods = periods

#
g.smooth = False
g.smooth_window = 5
g.smooth_order = 2
g.standardize = True
g.n_dimensions = 2
g.scatter_size = 600


#
g.process_data_circadian()



In [5]:
# dev periods
g.plot_3d = True
t1 = 18
t2 = 27
g.dev_windows = [t1,t2]
g.periods = [
        [16, t1],
        [t1, t2],
        [t2, 30],
]

#
g.circadian_plots()



Starting behavior:  foodhopper_proximity

starting: class:  adults
data.shape:  (6, 14, 24)
p: , temp.shape:  (0, 2) (2, 24)
p: , temp.shape:  (2, 11) (9, 24)
p: , temp.shape:  (11, 14) (3, 24)
idxs:  [[0, 6], [6, 12], [12, 18]]
stacked cl array:  (18, 24)
variance explained for 3pcs:  0.656924540046659
class temp size:  (6, 3)
class temp size:  (6, 3)
class temp size:  (6, 3)
0 vol:  101196653.60641488
1 vol:  13057611.962026786
2 vol:  8053921.68922192
0 1 0.15030065622039848
0 2 0.0011642902713699444
1 0 1.1648319377681708
1 2 0.07048234230520523
2 0 0.014629181141259023
2 1 0.11427117266706692

starting: class:  pups
data.shape:  (12, 14, 24)
p: , temp.shape:  (0, 2) (2, 24)
p: , temp.shape:  (2, 11) (9, 24)
p: , temp.shape:  (11, 14) (3, 24)
idxs:  [[0, 12], [12, 24], [24, 36]]
stacked cl array:  (36, 24)
variance explained for 3pcs:  0.8688520613303358
class temp size:  (12, 3)
class temp size:  (12, 3)
class temp size:  (12, 3)
0 vol:  135049.409505352
1 vol:  1715171.366250233

In [8]:
# compute bhattacharyya distance
g.selected_class = 'pups'  # 'pups', 'adults'...

g.optimize_t1_t2()

In [7]:
#
# g.show_convex_hull = True
# g.remove_outlier_point= False
# g.show_cohorts = True


# #
# g.run_pca()

In [8]:
#
# g.find_overlaps()

In [13]:
import os
# get total behavior for day vs. night cycle

g.get_circadian_total_behavior_sums()

        

[ 8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7 20 21 22 23]


Starting behavior:  foodhopper_proximity

starting: class:  adults
data.shape:  (6, 14, 24)
d.shape:  (14, 24)
dur_daytime:  28894.333333333332
dur_nighttime:  22168.666666666664
light ratio:  56.59  , std:  0.53
dark ratio:  43.41  , std:  0.46

starting: class:  pups
data.shape:  (12, 14, 24)
d.shape:  (14, 24)
dur_daytime:  28966.916666666664
dur_nighttime:  19639.166666666668
light ratio:  59.6  , std:  2.62
dark ratio:  40.4  , std:  2.53

starting: class:  pups_adults


In [30]:
# compute areas under the curve for each animal
g.get_area_under_curve()

temp_stack:  (6, 14)
temp_starts:  (2, 2)
[[0 3]
 [3 6]]
ks test:  KstestResult(statistic=1.0, pvalue=0.09999999999999999)
ttest:  Ttest_indResult(statistic=2.0072925072275902, pvalue=0.11515405792257753)


In [ ]:
#
g.show_convex_hull = True
g.remove_outlier_point= False
g.show_cohorts = False
g.run_pca()

In [113]:
#
g.find_overlaps()



In [94]:
d = np.load('/home/cat/Downloads/sex_npy_files/npy files/malepup_malepup_pairwise.npy')[None]

print (d)

np.save('/home/cat/Downloads/sex_npy_files/npy files/malepup_malepup_pairwise.npy', d)

[[0.85409747 1.51309115 4.16478603 2.21157815 2.93465807 1.91916357
  2.20043901 2.37760444 1.57626118 2.48152156 2.63308142 2.47293815
  2.43156419 2.13664209]]


In [36]:
#
g.run_umap()

(18, 2)


ValueError: 'c' argument has 4 elements, which is inconsistent with 'x' and 'y' with size 3.

In [10]:

d = np.load('/home/cat/code/gerbil/meta_data/fig3/malepup_malepup_pairwise.npy')

print (d.shape)

#np.save('/home/cat/code/gerbil/meta_data/fig3/malepup_malepup_pairwise.npy', d)


(1, 14)


In [120]:
d = np.load('/home/cat/code/gerbil/meta_data/fig4/pairwise_proximity_pups.npy')
print (d.shape)

plt.figure()

plt.imshow(d[0],
          aspect = 'auto',
)
plt.colorbar()

plt.figure()

plt.plot(d[0].mean(0))

print (d[0].mean(0).sum())
plt.title("Pup-pup average proximity (for some random pup pair)")
plt.ylabel("Time (sec)")  
plt.show()

(48, 14, 24)
771.0714285714287


In [26]:
g.n_dimensions = 2
g.fit_gmm_pca()



(48, 14)
(48, 2)


In [27]:
#


(48, 2)


In [151]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import ConvexHull
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

# Step 1: Generate or load your 3D data (replace this with your actual data)
np.random.seed(0)
data = np.random.rand(50, 3)  # 50 points in 3D

# Step 2: Compute the convex hull
hull = ConvexHull(data)
vertices = data[hull.vertices]  # Vertices of the convex hull

# get the ids of the vertices
# make a larger vertices array and fill in the missing vertices with zeros
vertices = np.zeros((data.shape[0],3))
vertices[hull.vertices] = data[hull.vertices]

print (vertices.shape)

#

# Step 3: Extract the valid edges and vertices from the convex hull
edges = []
for simplex in hull.simplices:
    n_bad = 0
    for v in simplex:
        #print (v)
        if v < 0 or v >= len(data):
            n_bad += 1

    if n_bad == 0:
        edges.append(simplex)

# Step 4: Create the 3D plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Step 5: Create a Poly3DCollection for the 3D polygon
poly3d = [[vertices[edge[0]], vertices[edge[1]], vertices[edge[2]]] for edge in edges]

ax.add_collection3d(Poly3DCollection(poly3d, 
                                     facecolors='black', 
                                     linewidths=1, 
                                     edgecolors='black', 
                                     alpha=0.25))

# Step 6: Set axis labels and display the plot
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')
ax.set_zlabel('Z-axis')

plt.show()


(50, 3)


In [254]:
import vedo

# Define the vertices of the first polyhedron
vertices1 = [
    [0, 0, 0],
    [1, 0, 0],
    [1, 1, 0],
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 1],
    [1, 1, 1],
    [0, 1, 1]
]

# Define the faces for the first polyhedron
faces1 = [
    [0, 1, 2, 3],  # Bottom face
    [4, 5, 6, 7],  # Top face
    [0, 1, 5, 4],  # Side 1
    [1, 2, 6, 5],  # Side 2
    [2, 3, 7, 6],  # Side 3
    [3, 0, 4, 7]   # Side 4
]

# Define the vertices of the second polyhedron
vertices2 = [
    [0.5, 0.5, 0],
    [1.5, 0.5, 0],
    [1.5, 1.5, 0],
    [0.5, 1.5, 0],
    [0.5, 0.5, 1],
    [1.5, 0.5, 1],
    [1.5, 1.5, 1],
    [0.5, 1.5, 1]
]

# Define the faces for the second polyhedron
faces2 = [
    [0, 1, 2, 3],  # Bottom face
    [4, 5, 6, 7],  # Top face
    [0, 1, 5, 4],  # Side 1
    [1, 2, 6, 5],  # Side 2
    [2, 3, 7, 6],  # Side 3
    [3, 0, 4, 7]   # Side 4
]

# Create the two polyhedron objects
polyhedron1 = vedo.shapes.Poly(vertices1, faces1)
polyhedron2 = vedo.shapes.Poly(vertices2, faces2)

# Compute the intersection between the two polyhedrons
intersection = polyhedron1.intersectWith(polyhedron2)

# Visualize the intersection
show(intersection)


AttributeError: module 'vedo.shapes' has no attribute 'Poly'